#!/bin/bash

VPLAY_NAME=vplay
VPLAY_VER=0.0.2

MUSIC_PATH=/home/pi/music/
DI_URL=http://listen.di.fm/public3/
LUB_URL=http://rzg.pl/player/

CMD_PLAY_TRANCE=trance
CMD_PLAY_VOCALTRANCE=vocaltrance
CMD_PLAY_CHILLOUT=chillout
CMD_PLAY_HOUSE=house
CMD_PLAY_ELECTRO=electro
CMD_PLAY_RZG=rzg
CMD_PLAY_RZ=rz
CMD_PLAY_ZG=rg
CMD_STOP=stop

music_type[0]=trance
music_type[1]=vocaltrance
music_type[2]=chillout
music_type[3]=house
music_type[4]=electro
music_type[5]=rzg
music_type[6]=rz
music_type[7]=rg

nofit_cnt=0

# Kill mplayer as we use it for playing.
function vplay_stop {
    pkill mplayer
    echo $VPLAY_NAME stopped
    exit 0
}

# Tell how to use the program.
function vplay_usage {
    echo Usage: $VPLAY_NAME '[options]'
    if [ -n "$1" ]; then
	exit "$1"
    fi
}

# Play music type given.
function vplay_play_music {

    case $1 in
	di)
	    mplayer -playlist $DI_URL$2.pls > /dev/null 2>&1 &
	    ;;

	lub)
	    mplayer -playlist $LUB_URL$2.m3u > /dev/null 2>&1 &
	    ;;

	mp3)
	    mplayer $MUSIC_PATH*$2* > /dev/null 2>&1 &
            ;;

	*)
	    vplay_usage -3
	    ;;
    esac
	
}

# Display all supported music types.
function vplay_music_types {
    echo $PLAY_NAME: follwing music types are supported:
    for i in "${music_type[@]}"
    do
	echo " -$i"
    done
    exit 0
}

# Help general header.
function vplay_help_footer {
    echo Report bugs to: '<http://github.com/voslak/vplay/issues>'
    echo $VPLAY_NAME home page: '<http://github.com/voslak/vplay>'
    echo General help using GNU software: '<http://www.gnu.org/gethelp/>'
}

# Opions supported.
function vplay_options {
    echo "Options:"
    echo "  --help	        Display this information"
    echo "  --version		Display $VPLAY_NAME version information"
    echo "  --musictypes		Display supported music types"
    echo "  --commands		Display commands supported TBD"
    echo ""
}


if [ -z "$1" ];
then
    vplay_usage -1
fi

for i in $@; do
    case $i in
	--version)
	    echo $VPLAY_NAME $VPLAY_VER
	    echo Copyright '(C)' 2013 SEITAZ
	    echo License GPLv3+: GNU GPL version 3 or later '<http://gnu.org/licenses/gpl.html>'
	    echo This is free software: you are free to change and redistribute it.
	    echo There is NO WARRANTY, to the extent permitted by law.
	    exit 0
	    ;;

	--help)
	    vplay_usage
	    vplay_options
	    vplay_help_footer
	    exit 0
	    ;;

	--musictypes)
	    vplay_music_types
	    ;;

	*)
	    let nofit_cnt++
    	    ;;
    esac
done
 
# Check selected music type/source
case $1 in
    $CMD_STOP)
	vplay_stop
	;;
    $CMD_PLAY_TRANCE)      ;&
    $CMD_PLAY_VOCALTRANCE) ;&
    $CMD_PLAY_CHILLOUT)    ;&
    $CMD_PLAY_HOUSE)       ;&
    $CMD_PLAY_ELECTRO)
	vplay_play_music di $1
	;;

    $CMD_PLAY_RZG) ;&
    $CMD_PLAY_RZ)  ;&
    $CMD_PLAY_RG)
	vplay_play_music lub $1
	;;

    *)
	vplay_play_music mp3 $1
	;;
esac

echo ======================================================
echo $VPLAY_NAME: Playing $1, enjoy!
echo ======================================================

exit 0

